// Auto-generated by scripts/generate-confession-timing.py
export type TimedWord = {
	text: string;
	start: number;
	end: number;
};

export type TimedLine = {
	id: string;
	text: string;
	start: number;
	end: number;
	words: TimedWord[];
};

export const confessionTiming = {
  "duration": 77.36,
  "stanzas": [
    [
      {
        "id": "s0-l0",
        "text": "I give thanks unto the Lord for He is good",
        "start": 0.0,
        "end": 2.44,
        "words": [
          {
            "text": "I",
            "start": 0.0,
            "end": 0.22
          },
          {
            "text": "give",
            "start": 0.22,
            "end": 0.38
          },
          {
            "text": "thanks",
            "start": 0.38,
            "end": 0.7
          },
          {
            "text": "unto",
            "start": 0.7,
            "end": 1.04
          },
          {
            "text": "the",
            "start": 1.04,
            "end": 1.28
          },
          {
            "text": "Lord",
            "start": 1.28,
            "end": 1.5
          },
          {
            "text": "for",
            "start": 1.5,
            "end": 1.8
          },
          {
            "text": "He",
            "start": 1.8,
            "end": 1.96
          },
          {
            "text": "is",
            "start": 1.96,
            "end": 2.18
          },
          {
            "text": "good",
            "start": 2.18,
            "end": 2.44
          }
        ]
      },
      {
        "id": "s0-l1",
        "text": "and His mercy endures forever.",
        "start": 2.44,
        "end": 4.64,
        "words": [
          {
            "text": "and",
            "start": 2.44,
            "end": 2.64
          },
          {
            "text": "His",
            "start": 2.64,
            "end": 3.1
          },
          {
            "text": "mercy",
            "start": 3.1,
            "end": 4.02
          },
          {
            "text": "endures",
            "start": 4.34,
            "end": 4.42
          },
          {
            "text": "forever",
            "start": 4.42,
            "end": 4.64
          }
        ]
      },
      {
        "id": "s0-l2",
        "text": "The Lord has redeemed my life from destruction.",
        "start": 4.64,
        "end": 7.72,
        "words": [
          {
            "text": "The",
            "start": 4.64,
            "end": 4.94
          },
          {
            "text": "Lord",
            "start": 4.94,
            "end": 5.34
          },
          {
            "text": "has",
            "start": 5.34,
            "end": 5.58
          },
          {
            "text": "redeemed",
            "start": 5.58,
            "end": 5.82
          },
          {
            "text": "my",
            "start": 5.82,
            "end": 6.08
          },
          {
            "text": "life",
            "start": 6.08,
            "end": 6.78
          },
          {
            "text": "from",
            "start": 7.26,
            "end": 7.52
          },
          {
            "text": "destruction",
            "start": 7.52,
            "end": 7.72
          }
        ]
      },
      {
        "id": "s0-l3",
        "text": "Blessed be the Lord who daily loads me with benefits,",
        "start": 7.72,
        "end": 11.06,
        "words": [
          {
            "text": "Blessed",
            "start": 7.72,
            "end": 7.88
          },
          {
            "text": "be",
            "start": 7.88,
            "end": 8.12
          },
          {
            "text": "the",
            "start": 8.12,
            "end": 8.36
          },
          {
            "text": "Lord",
            "start": 8.36,
            "end": 8.62
          },
          {
            "text": "who",
            "start": 8.62,
            "end": 8.96
          },
          {
            "text": "daily",
            "start": 8.96,
            "end": 9.36
          },
          {
            "text": "loads",
            "start": 9.36,
            "end": 9.76
          },
          {
            "text": "me",
            "start": 9.76,
            "end": 10.4
          },
          {
            "text": "with",
            "start": 10.7,
            "end": 10.86
          },
          {
            "text": "benefits",
            "start": 10.86,
            "end": 11.06
          }
        ]
      },
      {
        "id": "s0-l4",
        "text": "even the God of my salvation.",
        "start": 11.06,
        "end": 12.96,
        "words": [
          {
            "text": "even",
            "start": 11.06,
            "end": 11.3
          },
          {
            "text": "the",
            "start": 11.3,
            "end": 11.56
          },
          {
            "text": "God",
            "start": 11.56,
            "end": 11.72
          },
          {
            "text": "of",
            "start": 11.72,
            "end": 12.34
          },
          {
            "text": "my",
            "start": 12.76,
            "end": 12.84
          },
          {
            "text": "salvation",
            "start": 12.84,
            "end": 12.96
          }
        ]
      },
      {
        "id": "s0-l5",
        "text": "He has crowned me with loving-kindness",
        "start": 12.96,
        "end": 15.1,
        "words": [
          {
            "text": "He",
            "start": 12.96,
            "end": 13.52
          },
          {
            "text": "has",
            "start": 13.52,
            "end": 13.64
          },
          {
            "text": "crowned",
            "start": 13.64,
            "end": 13.86
          },
          {
            "text": "me",
            "start": 13.86,
            "end": 14.16
          },
          {
            "text": "with",
            "start": 14.16,
            "end": 14.66
          },
          {
            "text": "loving",
            "start": 14.66,
            "end": 14.94
          },
          {
            "text": "kindness",
            "start": 14.94,
            "end": 15.1
          }
        ]
      },
      {
        "id": "s0-l6",
        "text": "and His tender mercies.",
        "start": 15.1,
        "end": 16.74,
        "words": [
          {
            "text": "and",
            "start": 15.1,
            "end": 15.4
          },
          {
            "text": "His",
            "start": 15.4,
            "end": 16.32
          },
          {
            "text": "tender",
            "start": 16.52,
            "end": 16.52
          },
          {
            "text": "mercies",
            "start": 16.52,
            "end": 16.74
          }
        ]
      },
      {
        "id": "s0-l7",
        "text": "He satisfied my mouth with good things",
        "start": 16.74,
        "end": 19.28,
        "words": [
          {
            "text": "He",
            "start": 16.74,
            "end": 17.36
          },
          {
            "text": "satisfied",
            "start": 17.36,
            "end": 17.64
          },
          {
            "text": "my",
            "start": 17.64,
            "end": 17.92
          },
          {
            "text": "mouth",
            "start": 17.92,
            "end": 18.16
          },
          {
            "text": "with",
            "start": 18.16,
            "end": 18.54
          },
          {
            "text": "good",
            "start": 18.54,
            "end": 18.98
          },
          {
            "text": "things",
            "start": 18.98,
            "end": 19.28
          }
        ]
      },
      {
        "id": "s0-l8",
        "text": "so that my youth is renewed like eagles.",
        "start": 19.28,
        "end": 22.14,
        "words": [
          {
            "text": "so",
            "start": 19.28,
            "end": 19.64
          },
          {
            "text": "that",
            "start": 19.64,
            "end": 20.02
          },
          {
            "text": "my",
            "start": 20.02,
            "end": 20.28
          },
          {
            "text": "youth",
            "start": 20.28,
            "end": 20.68
          },
          {
            "text": "is",
            "start": 20.68,
            "end": 21.06
          },
          {
            "text": "renewed",
            "start": 21.06,
            "end": 21.28
          },
          {
            "text": "like",
            "start": 21.28,
            "end": 21.46
          },
          {
            "text": "eagles",
            "start": 21.98,
            "end": 22.14
          }
        ]
      }
    ],
    [
      {
        "id": "s1-l0",
        "text": "God has enlarged my steps under me",
        "start": 22.14,
        "end": 24.14,
        "words": [
          {
            "text": "God",
            "start": 22.14,
            "end": 22.46
          },
          {
            "text": "has",
            "start": 22.46,
            "end": 22.6
          },
          {
            "text": "enlarged",
            "start": 22.6,
            "end": 23.18
          },
          {
            "text": "my",
            "start": 23.18,
            "end": 23.42
          },
          {
            "text": "steps",
            "start": 23.42,
            "end": 23.78
          },
          {
            "text": "under",
            "start": 23.78,
            "end": 23.9
          },
          {
            "text": "me",
            "start": 23.9,
            "end": 24.14
          }
        ]
      },
      {
        "id": "s1-l1",
        "text": "that my feet did not slip.",
        "start": 24.14,
        "end": 25.76,
        "words": [
          {
            "text": "that",
            "start": 24.14,
            "end": 24.34
          },
          {
            "text": "my",
            "start": 24.34,
            "end": 24.68
          },
          {
            "text": "feet",
            "start": 24.68,
            "end": 24.96
          },
          {
            "text": "did",
            "start": 24.96,
            "end": 25.3
          },
          {
            "text": "not",
            "start": 25.3,
            "end": 25.48
          },
          {
            "text": "slip",
            "start": 25.48,
            "end": 25.76
          }
        ]
      },
      {
        "id": "s1-l2",
        "text": "I have pursued my enemies and overtaken them;",
        "start": 26.12,
        "end": 28.96,
        "words": [
          {
            "text": "I",
            "start": 26.12,
            "end": 26.22
          },
          {
            "text": "have",
            "start": 26.22,
            "end": 26.4
          },
          {
            "text": "pursued",
            "start": 26.4,
            "end": 26.86
          },
          {
            "text": "my",
            "start": 26.86,
            "end": 27.24
          },
          {
            "text": "enemies",
            "start": 27.24,
            "end": 27.66
          },
          {
            "text": "and",
            "start": 27.66,
            "end": 27.92
          },
          {
            "text": "overtaken",
            "start": 27.92,
            "end": 28.46
          },
          {
            "text": "them",
            "start": 28.46,
            "end": 28.96
          }
        ]
      },
      {
        "id": "s1-l3",
        "text": "neither did I turn again till they were consumed.",
        "start": 28.96,
        "end": 32.02,
        "words": [
          {
            "text": "neither",
            "start": 28.96,
            "end": 29.54
          },
          {
            "text": "did",
            "start": 29.54,
            "end": 29.88
          },
          {
            "text": "I",
            "start": 29.88,
            "end": 30.0
          },
          {
            "text": "turn",
            "start": 30.0,
            "end": 30.3
          },
          {
            "text": "again",
            "start": 30.3,
            "end": 30.74
          },
          {
            "text": "till",
            "start": 30.74,
            "end": 31.08
          },
          {
            "text": "they",
            "start": 31.08,
            "end": 31.22
          },
          {
            "text": "were",
            "start": 31.22,
            "end": 31.38
          },
          {
            "text": "consumed",
            "start": 31.38,
            "end": 32.02
          }
        ]
      },
      {
        "id": "s1-l4",
        "text": "God has girded me with strength for the battle.",
        "start": 32.66,
        "end": 35.18,
        "words": [
          {
            "text": "God",
            "start": 32.66,
            "end": 32.82
          },
          {
            "text": "has",
            "start": 32.82,
            "end": 33.2
          },
          {
            "text": "girded",
            "start": 33.2,
            "end": 33.52
          },
          {
            "text": "me",
            "start": 33.52,
            "end": 33.8
          },
          {
            "text": "with",
            "start": 33.8,
            "end": 34.04
          },
          {
            "text": "strength",
            "start": 34.04,
            "end": 34.3
          },
          {
            "text": "for",
            "start": 34.3,
            "end": 34.62
          },
          {
            "text": "the",
            "start": 34.62,
            "end": 34.76
          },
          {
            "text": "battle",
            "start": 34.76,
            "end": 35.18
          }
        ]
      },
      {
        "id": "s1-l5",
        "text": "He has subdued under me those that rose against me.",
        "start": 35.56,
        "end": 38.68,
        "words": [
          {
            "text": "He",
            "start": 35.56,
            "end": 35.6
          },
          {
            "text": "has",
            "start": 35.6,
            "end": 35.72
          },
          {
            "text": "subdued",
            "start": 35.72,
            "end": 36.38
          },
          {
            "text": "under",
            "start": 36.38,
            "end": 36.62
          },
          {
            "text": "me",
            "start": 36.62,
            "end": 36.72
          },
          {
            "text": "those",
            "start": 36.72,
            "end": 37.24
          },
          {
            "text": "that",
            "start": 37.24,
            "end": 37.48
          },
          {
            "text": "rose",
            "start": 37.48,
            "end": 37.76
          },
          {
            "text": "against",
            "start": 37.76,
            "end": 38.24
          },
          {
            "text": "me",
            "start": 38.24,
            "end": 38.68
          }
        ]
      }
    ],
    [
      {
        "id": "s2-l0",
        "text": "I am blessed of the Lord and",
        "start": 39.12,
        "end": 40.66,
        "words": [
          {
            "text": "I",
            "start": 39.12,
            "end": 39.14
          },
          {
            "text": "am",
            "start": 39.14,
            "end": 39.28
          },
          {
            "text": "blessed",
            "start": 39.28,
            "end": 39.64
          },
          {
            "text": "of",
            "start": 39.64,
            "end": 39.94
          },
          {
            "text": "the",
            "start": 39.94,
            "end": 40.06
          },
          {
            "text": "Lord",
            "start": 40.06,
            "end": 40.34
          },
          {
            "text": "and",
            "start": 40.34,
            "end": 40.66
          }
        ]
      },
      {
        "id": "s2-l1",
        "text": "favor compassed me as a shield.",
        "start": 40.66,
        "end": 42.66,
        "words": [
          {
            "text": "favor",
            "start": 40.66,
            "end": 41.08
          },
          {
            "text": "compassed",
            "start": 41.08,
            "end": 41.6
          },
          {
            "text": "me",
            "start": 41.6,
            "end": 41.98
          },
          {
            "text": "as",
            "start": 41.98,
            "end": 42.2
          },
          {
            "text": "a",
            "start": 42.2,
            "end": 42.3
          },
          {
            "text": "shield",
            "start": 42.3,
            "end": 42.66
          }
        ]
      },
      {
        "id": "s2-l2",
        "text": "The Lord has brought us into our wealthy place",
        "start": 43.1,
        "end": 45.62,
        "words": [
          {
            "text": "The",
            "start": 43.1,
            "end": 43.18
          },
          {
            "text": "Lord",
            "start": 43.18,
            "end": 43.46
          },
          {
            "text": "has",
            "start": 43.46,
            "end": 43.8
          },
          {
            "text": "brought",
            "start": 43.8,
            "end": 44.04
          },
          {
            "text": "us",
            "start": 44.04,
            "end": 44.3
          },
          {
            "text": "into",
            "start": 44.3,
            "end": 44.62
          },
          {
            "text": "our",
            "start": 44.62,
            "end": 44.82
          },
          {
            "text": "wealthy",
            "start": 44.82,
            "end": 45.2
          },
          {
            "text": "place",
            "start": 45.2,
            "end": 45.62
          }
        ]
      },
      {
        "id": "s2-l3",
        "text": "and now is the manifestation.",
        "start": 45.62,
        "end": 47.54,
        "words": [
          {
            "text": "and",
            "start": 45.62,
            "end": 46.22
          },
          {
            "text": "now",
            "start": 46.22,
            "end": 46.44
          },
          {
            "text": "is",
            "start": 46.44,
            "end": 46.74
          },
          {
            "text": "the",
            "start": 46.74,
            "end": 46.86
          },
          {
            "text": "manifestation",
            "start": 46.86,
            "end": 47.54
          }
        ]
      },
      {
        "id": "s2-l4",
        "text": "I am blessed in the city and in the field.",
        "start": 48.2,
        "end": 50.56,
        "words": [
          {
            "text": "I",
            "start": 48.2,
            "end": 48.3
          },
          {
            "text": "am",
            "start": 48.3,
            "end": 48.48
          },
          {
            "text": "blessed",
            "start": 48.48,
            "end": 48.84
          },
          {
            "text": "in",
            "start": 48.84,
            "end": 49.18
          },
          {
            "text": "the",
            "start": 49.18,
            "end": 49.24
          },
          {
            "text": "city",
            "start": 49.24,
            "end": 49.68
          },
          {
            "text": "and",
            "start": 49.68,
            "end": 49.92
          },
          {
            "text": "in",
            "start": 49.92,
            "end": 50.04
          },
          {
            "text": "the",
            "start": 50.04,
            "end": 50.16
          },
          {
            "text": "field",
            "start": 50.16,
            "end": 50.56
          }
        ]
      }
    ],
    [
      {
        "id": "s3-l0",
        "text": "The Lord is my shepherd and I shall not lack.",
        "start": 51.08,
        "end": 53.66,
        "words": [
          {
            "text": "The",
            "start": 51.08,
            "end": 51.16
          },
          {
            "text": "Lord",
            "start": 51.16,
            "end": 51.46
          },
          {
            "text": "is",
            "start": 51.46,
            "end": 51.68
          },
          {
            "text": "my",
            "start": 51.68,
            "end": 51.86
          },
          {
            "text": "shepherd",
            "start": 51.86,
            "end": 52.3
          },
          {
            "text": "and",
            "start": 52.3,
            "end": 52.72
          },
          {
            "text": "I",
            "start": 52.72,
            "end": 52.86
          },
          {
            "text": "shall",
            "start": 52.86,
            "end": 53.06
          },
          {
            "text": "not",
            "start": 53.06,
            "end": 53.34
          },
          {
            "text": "lack",
            "start": 53.34,
            "end": 53.66
          }
        ]
      },
      {
        "id": "s3-l1",
        "text": "I give generously and abundantly to every good work.",
        "start": 54.2,
        "end": 57.38,
        "words": [
          {
            "text": "I",
            "start": 54.2,
            "end": 54.22
          },
          {
            "text": "give",
            "start": 54.22,
            "end": 54.46
          },
          {
            "text": "generously",
            "start": 54.46,
            "end": 55.0
          },
          {
            "text": "and",
            "start": 55.0,
            "end": 55.28
          },
          {
            "text": "abundantly",
            "start": 55.28,
            "end": 56.1
          },
          {
            "text": "to",
            "start": 56.1,
            "end": 56.38
          },
          {
            "text": "every",
            "start": 56.38,
            "end": 56.64
          },
          {
            "text": "good",
            "start": 56.64,
            "end": 56.94
          },
          {
            "text": "work",
            "start": 56.94,
            "end": 57.38
          }
        ]
      },
      {
        "id": "s3-l2",
        "text": "All my needs are supplied.",
        "start": 57.38,
        "end": 59.74,
        "words": [
          {
            "text": "All",
            "start": 57.38,
            "end": 58.0
          },
          {
            "text": "my",
            "start": 58.0,
            "end": 58.3
          },
          {
            "text": "needs",
            "start": 58.3,
            "end": 58.78
          },
          {
            "text": "are",
            "start": 58.78,
            "end": 59.12
          },
          {
            "text": "supplied",
            "start": 59.12,
            "end": 59.74
          }
        ]
      }
    ],
    [
      {
        "id": "s4-l0",
        "text": "My going and my coming is blessed.",
        "start": 60.22,
        "end": 62.34,
        "words": [
          {
            "text": "My",
            "start": 60.22,
            "end": 60.4
          },
          {
            "text": "going",
            "start": 60.4,
            "end": 60.82
          },
          {
            "text": "and",
            "start": 60.82,
            "end": 61.02
          },
          {
            "text": "my",
            "start": 61.02,
            "end": 61.22
          },
          {
            "text": "coming",
            "start": 61.22,
            "end": 61.64
          },
          {
            "text": "is",
            "start": 61.64,
            "end": 61.94
          },
          {
            "text": "blessed",
            "start": 61.94,
            "end": 62.34
          }
        ]
      },
      {
        "id": "s4-l1",
        "text": "My family is blessed.",
        "start": 62.84,
        "end": 64.4,
        "words": [
          {
            "text": "My",
            "start": 62.84,
            "end": 63.06
          },
          {
            "text": "family",
            "start": 63.06,
            "end": 63.62
          },
          {
            "text": "is",
            "start": 63.62,
            "end": 63.9
          },
          {
            "text": "blessed",
            "start": 63.9,
            "end": 64.4
          }
        ]
      },
      {
        "id": "s4-l2",
        "text": "I am a blessing to my generation.",
        "start": 64.74,
        "end": 66.5,
        "words": [
          {
            "text": "I",
            "start": 64.74,
            "end": 64.98
          },
          {
            "text": "am",
            "start": 64.98,
            "end": 65.06
          },
          {
            "text": "a",
            "start": 65.06,
            "end": 65.12
          },
          {
            "text": "blessing",
            "start": 65.12,
            "end": 65.52
          },
          {
            "text": "to",
            "start": 65.52,
            "end": 65.76
          },
          {
            "text": "my",
            "start": 65.76,
            "end": 65.94
          },
          {
            "text": "generation",
            "start": 65.94,
            "end": 66.5
          }
        ]
      },
      {
        "id": "s4-l3",
        "text": "I am an eternal excellency and a joy of",
        "start": 67.22,
        "end": 70.44,
        "words": [
          {
            "text": "I",
            "start": 67.22,
            "end": 67.46
          },
          {
            "text": "am",
            "start": 67.46,
            "end": 67.66
          },
          {
            "text": "an",
            "start": 67.66,
            "end": 67.82
          },
          {
            "text": "eternal",
            "start": 67.82,
            "end": 68.1
          },
          {
            "text": "excellency",
            "start": 68.1,
            "end": 68.86
          },
          {
            "text": "and",
            "start": 68.86,
            "end": 69.62
          },
          {
            "text": "a",
            "start": 69.62,
            "end": 69.78
          },
          {
            "text": "joy",
            "start": 69.78,
            "end": 70.1
          },
          {
            "text": "of",
            "start": 70.1,
            "end": 70.44
          }
        ]
      },
      {
        "id": "s4-l4",
        "text": "many generations.",
        "start": 70.44,
        "end": 71.44,
        "words": [
          {
            "text": "many",
            "start": 70.44,
            "end": 70.7
          },
          {
            "text": "generations",
            "start": 70.7,
            "end": 71.44
          }
        ]
      }
    ],
    [
      {
        "id": "s5-l0",
        "text": "I am blessed at all times.",
        "start": 71.94,
        "end": 73.38,
        "words": [
          {
            "text": "I",
            "start": 71.94,
            "end": 72.02
          },
          {
            "text": "am",
            "start": 72.02,
            "end": 72.12
          },
          {
            "text": "blessed",
            "start": 72.12,
            "end": 72.42
          },
          {
            "text": "at",
            "start": 72.42,
            "end": 72.74
          },
          {
            "text": "all",
            "start": 72.74,
            "end": 72.94
          },
          {
            "text": "times",
            "start": 72.94,
            "end": 73.38
          }
        ]
      },
      {
        "id": "s5-l1",
        "text": "I am a king and a priest unto the Lord God Almighty.",
        "start": 73.58,
        "end": 77.36,
        "words": [
          {
            "text": "I",
            "start": 73.58,
            "end": 73.6
          },
          {
            "text": "am",
            "start": 73.6,
            "end": 73.7
          },
          {
            "text": "a",
            "start": 73.7,
            "end": 73.78
          },
          {
            "text": "king",
            "start": 73.78,
            "end": 74.16
          },
          {
            "text": "and",
            "start": 74.16,
            "end": 74.5
          },
          {
            "text": "a",
            "start": 74.5,
            "end": 74.72
          },
          {
            "text": "priest",
            "start": 74.72,
            "end": 75.08
          },
          {
            "text": "unto",
            "start": 75.08,
            "end": 75.8
          },
          {
            "text": "the",
            "start": 75.8,
            "end": 76.0
          },
          {
            "text": "Lord",
            "start": 76.0,
            "end": 76.22
          },
          {
            "text": "God",
            "start": 76.22,
            "end": 76.62
          },
          {
            "text": "Almighty",
            "start": 76.62,
            "end": 77.36
          }
        ]
      }
    ]
  ]
} as const;
