from __future__ import annotations

import json
import re
from pathlib import Path

from faster_whisper import WhisperModel

ROOT = Path(__file__).resolve().parents[1]
VIDEO = ROOT / "public/videos/confessions/daily-confession.mp4"
OUTPUT = ROOT / "src/content/daily-confession-timing.ts"

STANZAS = [
	[
		"I give thanks unto the Lord for He is good",
		"and His mercy endures forever.",
		"The Lord has redeemed my life from destruction.",
		"Blessed be the Lord who daily loads me with benefits,",
		"even the God of my salvation.",
		"He has crowned me with loving-kindness",
		"and His tender mercies.",
		"He satisfied my mouth with good things",
		"so that my youth is renewed like eagles.",
	],
	[
		"God has enlarged my steps under me",
		"that my feet did not slip.",
		"I have pursued my enemies and overtaken them;",
		"neither did I turn again till they were consumed.",
		"God has girded me with strength for the battle.",
		"He has subdued under me those that rose against me.",
	],
	[
		"I am blessed of the Lord and",
		"favor compassed me as a shield.",
		"The Lord has brought us into our wealthy place",
		"and now is the manifestation.",
		"I am blessed in the city and in the field.",
	],
	[
		"The Lord is my shepherd and I shall not lack.",
		"I give generously and abundantly to every good work.",
		"All my needs are supplied.",
	],
	[
		"My going and my coming is blessed.",
		"My family is blessed.",
		"I am a blessing to my generation.",
		"I am an eternal excellency and a joy of",
		"many generations.",
	],
	[
		"I am blessed at all times.",
		"I am a king and a priest unto the Lord God Almighty.",
	],
]


def tokenize(line: str) -> list[str]:
	return re.findall(r"[A-Za-z0-9']+", line)


def main() -> None:
	model = WhisperModel("base", device="cpu", compute_type="int8")
	segments, _ = model.transcribe(str(VIDEO), word_timestamps=True)

	whisper_words: list[dict[str, float | str]] = []
	for segment in segments:
		if not segment.words:
			continue
		for word in segment.words:
			text = word.word.strip()
			if text:
				whisper_words.append(
					{
						"text": text,
						"start": round(word.start, 2),
						"end": round(word.end, 2),
					}
				)

	while whisper_words and re.sub(r"[^a-z]", "", whisper_words[-1]["text"].lower()) in {
		"amen",
		"and",
	}:
		whisper_words.pop()

	word_index = 0
	timed_stanzas: list[list[dict]] = []

	for stanza_index, stanza in enumerate(STANZAS):
		timed_stanza: list[dict] = []
		for line_index, line in enumerate(stanza):
			display_words = tokenize(line)
			timed_words: list[dict] = []

			for display_word in display_words:
				if word_index >= len(whisper_words):
					timed_words.append(
						{"text": display_word, "start": 0, "end": 0}
					)
					continue

				whisper_word = whisper_words[word_index]
				word_index += 1
				timed_words.append(
					{
						"text": display_word,
						"start": whisper_word["start"],
						"end": whisper_word["end"],
					}
				)

			line_start = timed_words[0]["start"] if timed_words else 0
			line_end = timed_words[-1]["end"] if timed_words else line_start

			timed_stanza.append(
				{
					"id": f"s{stanza_index}-l{line_index}",
					"text": line,
					"start": line_start,
					"end": line_end,
					"words": timed_words,
				}
			)

		timed_stanzas.append(timed_stanza)

	duration = whisper_words[-1]["end"] if whisper_words else 79

	ts_content = (
		"// Auto-generated by scripts/generate-confession-timing.py\n"
		"export type TimedWord = {\n"
		"\treadonly text: string;\n"
		"\treadonly start: number;\n"
		"\treadonly end: number;\n"
		"};\n\n"
		"export type TimedLine = {\n"
		"\treadonly id: string;\n"
		"\treadonly text: string;\n"
		"\treadonly start: number;\n"
		"\treadonly end: number;\n"
		"\treadonly words: readonly TimedWord[];\n"
		"};\n\n"
		"export const confessionTiming = "
		+ json.dumps({"duration": duration, "stanzas": timed_stanzas}, indent=2)
		+ " as const;\n"
	)

	OUTPUT.write_text(ts_content, encoding="utf-8")
	print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
	main()
